### ISSUE TITLE
FInd a good threshold accuracy value for text recognition.

### ISSUE THREAD

**Issue by yzen** [mozilla/Bubo-Eye#15]
We should really only update the alt text with possible text if we are confident in tesseract's accuracy. Lets figure out what would be the lowest value we can consider when using the results. Below that value we should not use the text and instead mention something to the user about not getting reliable results.

**Comment by hamletv** [comment]
It’s difficult to assign a threshold percentage number to Tesseract’s scanning results with certainty for every use. It would be an arbitrary number given the number of variables involved in each case. Tesseract was originally developed to scan documents, not images. High contrast, high resolution documents will provide excellent (still not perfect) results.   

Tesseract results accuracy can be largely improved prior to image scanning. There are different image pre-processing methods that can be used to improve the accuracy of the output. We should use the methods listed below to get the current image to be as high contrast, high resolution as possible and then feel more comfortable assigning a conservative 85% as the lowest confidence value that can be allowed to be passed to the user.

Based on my testing of Tesseract, results passed to the user that meet this confidence value can still be of use, an understanding/gist of what’s in the image content can be accessed if not fully grasped at 85% confidence. There is some value in that; some accessibility is better than no accessibility.

- Image rescaling: tesseract works best on images that are 300 dpi or more. Since we’re dealing with web images they’ll generally be 72 dpi +/-. In the interest of improving accuracy the extension may need a way to enlarge these images before scanning, which may delay results.
- Binarisation: convert the image to black and white which would hopefully remove some color “noise”.
- Noise removal: Tesseract only removes some noise. Finding a way to pass as “clean” / noise-free of an image as possible prior to scanning will improve results.
- Rotation of text/image so it’s in as straight (horizontal) of a line as possible will allow boxing (recognition) of content to be more accurate, thereby giving better results for each character. The more accurate the characters are individually boxed/recognized, the less fixing at the word level is required, the more accurate the results will be.
- Segmentation: change segmentation mode from full page (default) to a smaller region. Focus on the text areas only when possible and leave out other parts of the image that may just contribute noise.

**Comment by hamletv** [comment]
yzen -  please review at your earliest convenience. Thanks!

**Comment by yzen** [comment]
This is good research. Thanks for looking into it. If 85% seems like a good conservative threshold, we should go with it for the initial version of the add-on. Different strategies that you outlined above should be split into separate issues and tackled independently. 

For the 1.0 milestone we should simply ignore Tesseract results if the % is less than 85 (and put meaningful description instead e.g. Could not recognize meaningful text or something like that).
