### ISSUE TITLE
Investigate training of tesseract language pack.

### ISSUE THREAD

**Issue by yzen** [mozilla/Bubo-Eye#16]
Right now tesseract's performance is not so good, especially against memes and fonts that are bright with dark outline. If we are able to load custom trained data along with the extension, we could train our extension to become much better suited for our use case.

**Comment by hamletv** [comment]
**Training Tesseract**

Tesseract training is possible and we can load custom trained data files with the extension. In this particular case the "eng" language data file will need to be retrained with the Impact font files included. This is the font typically used in memes. Since we are currently only dealing with images using English text, the "recognize" method of Tesseract will not need the optional parameter used for the language (English is default).

It is possible that training Tesseract by changing to a bright font color and/or adding an outline will improve the scanning of bright fonts with dark outlines. Training itself involves running Tesseract on selected images that contain the desired font (which in theory can be dark or light colored fonts; with or without outlines); creating box files of each glyph of the font; manually correcting the glyphs Tesseract scanned with the use of software (QT Box Editor) to change an "O" that was originally a "0" or vice versa. The corrected box files are then converted and loaded as new trained files into Tesseract.

**Source training data for Tesseract in various languages is found here:**
https://github.com/tesseract-ocr/langdata

To re-create the training of a single language, _lang_, the following is needed:
* All the data in the _lang_ directory.
* The corresponding unicharset/xheights files for the script(s) used by _lang_.
* All the remaining non-lang-specific files in the top-level directory, such as _font_properties_.
* You also need to obtain the fonts needed to train the language. In our case, Impact, a widely available font.

**langPath (local installation/custom trained data files):**
A string specifying the location of the tesseract language (or custom trained) files, with default value 'https://cdn.rawgit.com/naptha/tessdata/gh-pages/3.02/'. We're working with local files so this will not be our default path. Language file URLs are calculated according to the formula langPath + langCode + '.traineddata.gz'. Set this string before calling Tesseract.recognize and Tesseract.detect if you want Tesseract.js to use different language files.

**Comment by hamletv** [comment]
yzen -  please review at your earliest convenience. Thanks!

**Comment by yzen** [comment]
This looks promising, though probably post 1.0 version. I'm curious if you tried it, if not, might be something to look at after we publish the first version on AMO.

**Comment by hamletv** [comment]
I did not try it yet. I will set it up and tinker outside of branch/repo just to familiarize myself with it.
